# Base configuration file
defaults:
  - _self_
  - data: text8
  - model: sundae_diffusion_generation

loader:
  batch_size: 256
  global_batch_size: 256
  num_workers: 4


optimizer:
  learning_rate: 1e-5
  betas: [0.9, 0.999]
  eps: 1e-6
  weight_decay: 0.1
  
seed: 42
mode: train
compile: false
config_optimizer_and_batch_automatically: false
save_model: false
save_model_path: "model.pt"

unroll_steps: 3

sample:
  temperature: 0.4
  sample_proportion: 0.3
  sample_frequency: 1
  steps: 16
  min_steps: 10
  nb_samples: 4

checkpointing:
  resume_from_ckpt: false
  resume_ckpt_path: null

wandb:
  project: sundae-diffusion-improvement
  notes: ""
  entity: "claire-labo"
  group: null
  job_type: null
  name: ${model.type}-${data.name}-basic
  tags: