data:
  name: 'wmt14-ende-toy'
  root: 'data/wmt14'
  source_sequence_length: 128
  target_sequence_length: 128
  vocabulary_size: 40001
  shared_tokenizer_path: "tokenizers/wmt14-deen-shared-40k"
  pad_token: 1
  bos_token: 0
  eos_token: 2
  reverse: false
  max_length: 128

  loader:
    batch_size: 128
    global_batch_size: 128
    num_workers: 4

model:
  type: "toy-mt-hf-sundae"
  embedding_dim: 512
  nb_layers: 6
  nb_heads: 8
  downsampled_target_length: 64
  target_length_prediction_hidden_dim: 128
  label_smoothing: 0.1
  length_loss_weight: 1.0
  dropout: 0.1
  feedforward_dim: 2048

  min_lr: 1e-7
  peak_lr: 1e-4
  warmup_steps: 5000



  trainer:
    _target_: lightning.pytorch.Trainer
    # max_epochs: 15
    log_every_n_steps: 1
    check_val_every_n_epoch: null
    val_check_interval: 100
    num_sanity_val_steps: 0
    max_steps: 300000
    precision: "bf16-mixed"
    # precision: "32-true"
    strategy: "ddp"
    gradient_clip_val: 50.0
    enable_checkpointing: true
    accumulate_grad_batches: ${eval:4096 // ${loader.global_batch_size}}
    callbacks:
      - _target_: callbacks.TranslationSamplingCallback
        sample_frequency: 100
        nb_samples: ${sample.nb_samples} 
      - _target_: lightning.pytorch.callbacks.ModelCheckpoint
        dirpath: ${hydra:runtime.output_dir}/checkpoints
        filename: "{epoch:02d}-{step:08d}"
        save_last: true
        save_top_k: 10
        monitor: "step"
        mode: "max"

loader:
  batch_size: ${data.loader.batch_size}
  global_batch_size: ${data.loader.global_batch_size}
  num_workers: ${data.loader.num_workers}

optimizer:
  learning_rate: 1e-5
  betas: [0.9, 0.999]
  eps: 1e-6
  weight_decay: 0.1
  
seed: 42
mode: train
compile: false
config_optimizer_and_batch_automatically: false
save_model: false
save_model_path: "model.pt"

unroll_steps: 2

sample:
  temperature: 0.6
  sample_proportion: 0.3
  sample_frequency: 1
  steps: 16
  nb_samples: 1
  trim_eos: false
  num_samples: 16

checkpointing:
  resume_from_ckpt: false
  resume_ckpt_path: null

wandb:
  project: sundae-diffusion-improvement
  notes: ""
  entity: "claire-labo"
  group: null
  job_type: null
  name: ${model.type}-${data.name}-basic
  tags: