type: "sundae-diffusion-generation"
embedding_dim: 512
nb_layers: 12
nb_heads: 8
use_scalenorm: true
use_glu: true
use_rotary: true

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: 1
  log_every_n_steps: 1
  val_check_interval: 1.0
  precision: 32
  enable_checkpointing: true
  callbacks:
    - _target_: callbacks.TextSamplingCallback
      sample_frequency: 500
      nb_samples: ${sample.nb_samples} 